export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';
export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';
export const TOGGLE_FAVORITE_DROPDOWN = 'TOGGLE_FAVORITE_DROPDOWN';
